# Generated by Django 4.1.6 on 2023-06-05 06:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_like_product_alter_like_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='details',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
