# Generated by Django 4.1.6 on 2023-06-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_comment_details'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('product', 'user'), name='unique_like'),
        ),
    ]
